apiVersion: 1

groups:
  - name: signalops-alerts
    interval: 1m
    orgId: 1
    folder: SignalOps
    rules:
      - uid: error-rate-high
        title: High Error Rate (>5%)
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: Prometheus
            model:
              expr: sum(rate(http_server_duration_count{http_status_code=~"5.."}[5m])) / sum(rate(http_server_duration_count[5m]))
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: Error rate is above 5% for 5 minutes
          summary: High error rate detected
        labels:
          severity: warning
          team: backend

      - uid: high-latency
        title: High P95 Latency (>2s)
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: Prometheus
            model:
              expr: histogram_quantile(0.95, sum by (le) (rate(http_server_duration_bucket[5m]))) > 2
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: P95 latency exceeds 2 seconds
          summary: High latency detected
        labels:
          severity: warning
          team: backend

